services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: is-lc-app
    container_name: is-lc-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - is-lc-network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: is-lc-nginx
    ports:
      - "9030:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - is-lc-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: is-lc-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: is-lc
      MYSQL_USER: is-lc
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - is-lc-network
    ports:
      - "3303:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: is-lc-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: is-lc
      PMA_PASSWORD: secret
    ports:
      - "9031:80"
    networks:
      - is-lc-network
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: is-lc-mailhog
    ports:
      - "1025:1025"  # smtp
      - "8025:8025"  # web ui
    networks:
      - is-lc-network

volumes:
  db_data:
  vendor_data:
  node_modules:

networks:
  is-lc-network:
    driver: bridge
